-- apply changes
create table ${my_table_name} (
  id                            integer generated by default as identity not null,
  name                          varchar(255),
  constraint pk_${my_table_name} primary key (id)
);
