-- apply changes
create table m1 (
  id                            integer generated by default as identity not null,
  name                          varchar(255),
  constraint pk_m1 primary key (id)
);
